// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5HFa1qLAXWp1IykBRdvRI2EaGSiTeo8',
    appId: '1:282796537878:web:c784e0c6a55da8cac91d37',
    messagingSenderId: '282796537878',
    projectId: 'guru-ai-sahayak',
    authDomain: 'guru-ai-sahayak.firebaseapp.com',
    storageBucket: 'guru-ai-sahayak.firebasestorage.app',
    measurementId: 'G-1Q7WLM9PXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAg8yfRXlmaz4Y0YcVfdARzqcdNlDtTOo',
    appId: '1:282796537878:android:d4b39ed61b0c290fc91d37',
    messagingSenderId: '282796537878',
    projectId: 'guru-ai-sahayak',
    storageBucket: 'guru-ai-sahayak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdiu41EOxO9IRvyItyztauZbvPtT2PVhg',
    appId: '1:282796537878:ios:11046d89dfc2154dc91d37',
    messagingSenderId: '282796537878',
    projectId: 'guru-ai-sahayak',
    storageBucket: 'guru-ai-sahayak.firebasestorage.app',
    iosBundleId: 'com.example.guruAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdiu41EOxO9IRvyItyztauZbvPtT2PVhg',
    appId: '1:282796537878:ios:11046d89dfc2154dc91d37',
    messagingSenderId: '282796537878',
    projectId: 'guru-ai-sahayak',
    storageBucket: 'guru-ai-sahayak.firebasestorage.app',
    iosBundleId: 'com.example.guruAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc5HFa1qLAXWp1IykBRdvRI2EaGSiTeo8',
    appId: '1:282796537878:web:debae39dc7c8d084c91d37',
    messagingSenderId: '282796537878',
    projectId: 'guru-ai-sahayak',
    authDomain: 'guru-ai-sahayak.firebaseapp.com',
    storageBucket: 'guru-ai-sahayak.firebasestorage.app',
    measurementId: 'G-T4563CPYMB',
  );
}
